export function printHelp() {
  console.log([
    'code-doctrine',
    '',
    'CLI package manager for decentralized code doctrine packages.',
    '',
    'Usage:',
    '  code-doctrine install <author|path> [opencode|pi|all] [...flags]',
    '  code-doctrine resolve <author|path>',
    '  code-doctrine info <author|path>',
    '  code-doctrine fork <author|path> [dest-dir] [--force]',
    '  code-doctrine search [query]',
    '  code-doctrine doctor [author|path]',
    '  code-doctrine spec',
    '  code-doctrine --help',
    '',
    'Examples:',
    '  code-doctrine install kamilchm opencode --project',
    '  code-doctrine install ./my-doctrine opencode --project',
    '  code-doctrine install ./my-doctrine pi --project',
    '  code-doctrine fork kamilchm ./my-doctrine',
    '  code-doctrine resolve kamilchm',
    '  code-doctrine info ./my-doctrine',
    '  code-doctrine search',
    '  code-doctrine doctor kamilchm',
    '',
    'Resolution strategy (v1):',
    '  1. Try npm package @<author>/code-doctrine',
    '  2. Fall back to github:<author>/code-doctrine',
    '  3. Or install directly from a local doctrine directory path',
  ].join('\n'));
}
